# Generated by Django 5.2.5 on 2025-08-29 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='released_date',
            new_name='release_year',
        ),
    ]
